# Generated by Django 5.1.4 on 2025-01-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transactions",
            "0002_alter_transaction_category_alter_transaction_amount_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlysummary",
            name="balance",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="monthlysummary",
            name="total_expense",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="monthlysummary",
            name="total_income",
            field=models.IntegerField(),
        ),
    ]
